spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#  datasource:
#    url: jdbc:postgresql://localhost:5432/yarnstore
#    username: postgres
#    password: pass
#    driverClassName: org.postgresql.Driver
